### ISSUE TITLE
Detect when ship is sinked?

### ISSUE THREAD

**Issue by ajan1** [nightspirit/battleship.io#1]
Could it possible to add sinked ship feature?

**Comment by nightspirit** [comment]
Hi @ajan1 

Sorry for late response. I modify the source code and you should be able to get the information from "engage" event.

``` javascript
{
   offence:<id>,
   defence:<id>,
   target:<coordinates>,
   result:<HIT|MISS>
   sunk:<ship.type> // if any ship sunk, otherwise empty string
}
```

So if you get result as "HIT" and the sunk is not the empty string then you can tell that ship is dead.

The possible ship types are as followed:

> carrier, battleship, submarine, cruiser, patrolboat
